services:
  - type: web
    name: learnos-buddy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py && python main.py
    envVars:
      - key: PORT
        value: 7860
